twitter:
  username: ""
  consumer_key: ""
  consumer_secret: ""
  access_token: ""
  access_token_secret: ""
reddit:
  username: ""
  password: ""
  sub_reddit: ""
  client_id: ""
  client_secret: ""
  user_agent: ""
